# Generated by Django 4.2.7 on 2024-05-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
