# Generated by Django 3.2.19 on 2023-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leave_leavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='defaultdays',
            field=models.PositiveIntegerField(default=30, verbose_name='Leave days per year'),
        ),
    ]
