# Generated by Django 4.2.3 on 2023-07-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_alter_leave_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'permissions': [('can_approve_leave', 'Can approve leave'), ('can_reject_leave', 'Can reject leave')]},
        ),
    ]
