# Generated by Django 4.2.3 on 2023-07-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leave_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-created'], 'verbose_name': 'Leave', 'verbose_name_plural': 'Leaves'},
        ),
    ]
