# Generated by Django 3.2.19 on 2023-06-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leave_defaultdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='Yourleaveremainderthatyear',
            field=models.PositiveIntegerField(default=0, verbose_name='Leave days remaining that year'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leavedaysalreadyconsumed',
            field=models.PositiveIntegerField(default=0, verbose_name='Leave days already consumed in that year'),
        ),
    ]
