# Generated by Django 3.2.19 on 2023-06-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20230613_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='defaultdays',
            new_name='default_leave_days',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='Yourleaveremainderthatyear',
            new_name='remaining_leave_days',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='leavedaysalreadyconsumed',
            new_name='taken_leave_days',
        ),
    ]
