# Generated by Django 3.2.19 on 2023-06-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20230614_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
    ]
