# Generated by Django 4.2.3 on 2023-07-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(blank=True, help_text='Give some additional information for leave', max_length=255, null=True, verbose_name='Reason for Leave'),
        ),
    ]
