# Generated by Django 4.2.3 on 2023-08-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_remove_leave_is_recommended_alter_leave_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_days_carried_forwards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='total_leave_days_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
