# Generated by Django 3.2.19 on 2023-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_alter_leave_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='default_leave_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_days_remaining',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_days_taken',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('annual', 'annual'), ('sick', 'Sick Leave')], default='sick', max_length=25, null=True),
        ),
    ]
