# Generated by Django 4.2.3 on 2023-08-08 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leave_leave_days_carried_forwards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_days_carried_forwards',
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_days_carried_forward',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
    ]
