# Generated by Django 4.2.3 on 2023-08-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_remove_leave_leave_days_carried_forwards_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='default_leave_days',
            new_name='default_annual_leave_days',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='total_leave_days_available',
        ),
    ]
