# Generated by Django 4.2.3 on 2023-08-08 09:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0010_rename_default_leave_days_leave_default_annual_leave_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_days_carried_forward',
        ),
        migrations.CreateModel(
            name='CarriedForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_start', models.DateField()),
                ('leave_days_carried_forward', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(15)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
