# Generated by Django 4.2.3 on 2023-08-09 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_remove_leave_leave_days_carried_forward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='default_annual_leave_days',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_days_remaining',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_days_taken',
        ),
    ]
