# Generated by Django 4.2.3 on 2023-08-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_remove_leave_total_leave_days_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='total_leave_days_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='CarriedForward',
        ),
    ]
