# Generated by Django 4.2.3 on 2023-08-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0016_remove_leave_total_leave_days_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='total_leave_days_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
