# Generated by Django 4.2.3 on 2023-08-10 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_financialyear_end_date_and_more'),
        ('leave', '0017_leave_total_leave_days_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriedforward',
            name='financial_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.financialyear'),
        ),
    ]
