# Generated by Django 4.2.3 on 2023-08-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0018_alter_carriedforward_financial_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField()),
                ('holiday_type', models.CharField(choices=[('public', 'Public Holiday'), ('company', 'Company Holiday')], max_length=20)),
            ],
        ),
    ]
