# Generated by Django 4.2.3 on 2023-08-29 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_holiday_holiday_name_alter_holiday_holiday_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave.holiday'),
        ),
    ]
