# Generated by Django 4.2.3 on 2023-10-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0021_leave_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='holiday_date',
            field=models.DateField(help_text='New holiday', null=True, verbose_name='Holiday Date'),
        ),
    ]
