# Generated by Django 3.2.19 on 2023-06-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200904_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee ID Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full-Time', max_length=115, null=True, verbose_name='Employee Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=250, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=250, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='othername',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Othername (optional)'),
        ),
    ]
