# Generated by Django 3.2.19 on 2023-06-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20230609_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name', 'created'], 'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employeeid',
        ),
        migrations.AddField(
            model_name='employee',
            name='peronal_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Personal Number'),
        ),
    ]
