# Generated by Django 4.2.7 on 2024-05-13 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2024, 7, 1))),
                ('end_date', models.DateField(default=datetime.date(2024, 7, 1))),
            ],
        ),
    ]
