# Generated by Django 4.2.3 on 2023-08-10 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 7, 1)),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 7, 1)),
        ),
    ]
