# Generated by Django 4.2.7 on 2024-01-16 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_financialyear_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialyear',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 7, 1)),
        ),
        migrations.AlterField(
            model_name='financialyear',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 7, 1)),
        ),
    ]
